version: '3'
services:
  ### Postgres Database for simple-spring-ecommerce
  service-simple-ecommerce:
    container_name: container-simple-ecommerce
    image: postgres:15.4
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_simple_ecommerce
      POSTGRES_USER: popehiflo
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5430"
    expose:
      - 5432
    command: -p 5432